# clean requirements.txt
# conda create --name hydra python=3.7 
# conda activate hydra 
# pip install lightning-grid --upgrade
# pip install hydra-core
# pip install hydra
# pip install git+https://github.com/pytorch/hydra-torch
# pip freeze > requirements.txt
# 
# git add .
# git commit -m "requirements.txt for hydra"
# git push
# grid train --config grid-hydra-01.yaml --ignore_warnings minst-hydra-01.py
compute:
  provider:
    credentials: cc-qdfdk
    region: us-east-1
    vendor: aws
  train:
    cpus: 1
    disk_size: 200
    gpus: 0
    instance: t2.medium
    max_nodes: 10
    memory: null
    nodes: 0
    scale_down_seconds: 1800
#    distributed: false
    framework: "lightning"
    datastore_name: mnist        # Datastore name to use 
    datastore_version: 2          # Datastore version number
    datastore_mount_dir: /datastores/mnist     # Where to mount the datastore
    use_spot: true               # If we should use spot instances
    # Actions need to be passed as one command
    # per line.
    actions:
      # on_image_build:
      # below fails with bug switch to requirements. txt
      # failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 14: unknown instruction: 'PIP
      #  - pip install hydra-core
      #  - pip install hydra
      #  - pip install git+https://github.com/pytorch/hydra-torch
      on_before_training_start:
        - conda info --envs
        - pwd
        - df -kH
hyper_params:
  settings:
    strategy: random_search     # either random_search or grid_search
    trials: 1                   # only used in random_search
  params:
    data_dir: /datastores/mnist
    lr: uniform(0.001, 0.008, 10)

